### ISSUE TITLE
Add Browse Files button for the Transcript panel

### ISSUE THREAD

**Issue by Carsonthemonkey** [Carsonthemonkey/GIST#40]

**Comment by katberge** [comment]
part of commit #d9741e65eff37897a63ee36587201250bd3a1627 (Removes gray window when drag stops) contains what fixed it on chrome

**Comment by Carsonthemonkey** [comment]
@katberge I can't seem to get the new file drop area to be the right size when the screen size changes. Might need your CSS expertise on this.
